### ISSUE TITLE
pyeapi.api.vlans not working

### ISSUE THREAD

**Issue by theotherguy2175** [arista-eosplus/pyeapi#250]
ImportError: unable to import module pyeapi.api.vlans

Most of the features of the pyeapi works just fine but why would the vlans module not work? Is there something I need to enable on the switch?

**Comment by dlyssenko** [comment]
Hi @theotherguy2175,
could you please provide a bit more of a context? what branch of pyeapi do you use (master, develop?), what python (2, 3?). Also, steps to reproduce/trigger the issue?

**Comment by theotherguy2175** [comment]
I am on python 3.10.9
Using the latest pyeapi master


Just replicating the example from the wiki:

# create a connection to the node
import pyeapi
node = pyeapi.connect_to('veos01')

# get the instance of the API (in this case vlans)
vlans = node.api('vlans')

# return all vlans from the node
vlans.getall()


And it gives the aforementioned error.

**Comment by dlyssenko** [comment]
Hi @theotherguy2175, sorry for a delay replying.

3.10.x has removed many deprecations and broke many features that used to work in `master` branch with python 3.9.x, e.g.: `Iterable` has been moved from under `collections` to `collections.abc`, TLS stack has been updated with stronger security setting, which broke prior ciphers, etc.

So, using `master` with 3.10.x is not a good idea, though I'm surprised you'e got that far. When I tried `master` branch with 3.10.9 for me even `import pyeapi` failed:
```
python3
Python 3.10.9 (main, Feb 10 2023, 14:43:50) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyeapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
...
AttributeError: module 'collections' has no attribute 'Iterable'
```

Your options would be:
- use `master` branch with python 3.9.x
- use `develoop` branch with 3.10.x (better option).

Though the issue you're reporting is not strictly related to the compatibility issue of `master` with 3.10.x (quite likely it might persist even with `deelop` branch). Typically you get `ImportError` due to faulty installation or an invalid path. 

with that I'll be closing this issue, as it's not a problem with the pyeapi (verified on my machine)
